# Generated by Django 5.1.2 on 2024-10-23 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_agreement_declaration_agreementparticipant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declaration',
            old_name='content',
            new_name='body',
        ),
        migrations.CreateModel(
            name='DeclarationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.declaration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
