# Generated by Django 5.1.3 on 2024-11-19 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_individual_id_remove_legalentity_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='content',
            new_name='body',
        ),
    ]
