# Generated by Django 5.1.3 on 2024-11-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_content_agreement_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgreementParticipant',
            new_name='AgreementParty',
        ),
    ]
