# Generated by Django 5.1.3 on 2024-11-20 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_agreementparty_agreement_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposalparty',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='proposalparty',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='proposalparty',
            name='user',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='agreement',
        ),
        migrations.AddField(
            model_name='agreement',
            name='proposal',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.proposal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agreement',
            name='user1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agreements_as_user1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agreement',
            name='user2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agreements_as_user2', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AgreementParty',
        ),
        migrations.DeleteModel(
            name='ProposalParty',
        ),
    ]
