# Generated by Django 5.1.3 on 2024-11-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_proposalparty_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
    ]
