# Generated by Django 5.1.3 on 2024-11-21 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_proposal_is_finalized_proposal_has_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='receiver',
            new_name='user',
        ),
    ]
