# Generated by Django 5.1.3 on 2024-11-21 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_receiver_notification_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agreement',
        ),
    ]
