# Generated by Django 5.1.3 on 2024-11-21 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_agreement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proposal',
            new_name='Agreement',
        ),
    ]
