# Generated by Django 5.1.3 on 2024-11-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_proposal_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
    ]
