# Generated by Django 5.1.3 on 2024-11-21 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_created_at_agreement_proposed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='proposal',
            new_name='agreement',
        ),
    ]
