# Generated by Django 5.1.3 on 2024-11-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_proposal_notification_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('proposal', 'Agreement Proposal Notification'), ('letter', 'Letter Notification'), ('agreement decision', 'Agreement Decision Notification')], max_length=20),
        ),
    ]
