// src/pages/Home.jsx

import React from 'react';
import '@/styles/Home.module.css'; // Example of using alias for styles

const Home = () => {
  return (
    <div className="home">
      <header>
        <h1>InterId</h1>
        <p><em>A Network Platform for Civil Actions</em></p>
      </header>
      
      <section>
        <h2>Overview</h2>
        <p>It's all about:</p>
        <ul>
          <li>Open International ID</li>
          <li>Public Declarations</li>
          <li>Formal Agreements</li>
        </ul>
      </section>
      
      <section>
        <h2>Abstract</h2>
        <p><strong>InterId</strong> is a network platform designed for users (individuals or legal entities) to register civil actions, such as public declarations or agreements between two or more users.</p>
      </section>
      
      <section>
        <h2>Open International ID</h2>
        <ul>
          <li>A <strong>unique</strong> and <strong>immutable</strong> identifier automatically generated by the platform.</li>
          <li>Instead of selecting a username, this ID will serve as the person's permanent identifier internationally on the platform.</li>
          <li>Users are <strong>required</strong> to use their real names.</li>
          <li>The platform is intended for <strong>formal civil actions</strong>, ensuring authenticity in interactions.</li>
          <li>The user's profile is not shown publicly unless he/she makes a public declaration or a public agreement.</li>
        </ul>
      </section>
      
      <section>
        <h2>Public Declarations</h2>
        <p>A formal statement made by an individual or entity to announce or document a significant action, decision, or event, which is intended to be accessible to the public, ensuring transparency and accountability. Examples include business name changes, property transfers, legal notifications, donation announcements, etc.</p>
      </section>
      
      <section>
        <h2>Formal Agreements</h2>
        <ul>
          <li>Formal agreements remain <strong>private</strong> unless <strong>all parties agree</strong> to make them public.</li>
          <li>Only those granted access by one of the parties will be able to view such agreements.</li>
          <li>Legal entities can provide <strong>adhesion contracts</strong> for customers, allowing them to sign these contracts electronically.</li>
        </ul>
      </section>
      
      <section>
        <h2>Rules</h2>
        <ul>
          <li>Users on InterId <strong>cannot delete</strong> any content. However, it can be altered, but the historic record will remain publicly available for consultation.</li>
          <li>The declarant may allow comments on their declarations, and users can optionally delete their own comments.</li>
        </ul>
      </section>
    </div>
  );
};

export default Home;